kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "refarch-uiux-angular-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/saroj3k/refarch-uiux-angular"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile
