node('nodejs10') {
  stage ('checkout') {
    checkout scm
  }
  /* Set to OD internal registry */
  stage ('install modules'){
    sh '''
      npm config set registry http://build-repo.corp.odfl.com:8081/artifactory/api/npm/js-repo/
      npm install --verbose -d 
      npm install --save classlist.js
    '''
  }


/*  Comment out the Test scripts
try{
    stage ('test') {
      sh '''
        ls -l /opt/google/chrome/chrome-sandbox
        $(npm bin)/ng test --single-run --browsers Chrome_no_sandbox
      '''
    }
  } finally {
    junit "test-results.xml"
  }
  stage ('code quality'){
    sh '$(npm bin)/ng lint'
  }
*/

  /* the prod build fails as some of the permissions are wonky, so try with dev build
      sh '$(npm bin)/ng build --prod --build-optimizer'
      commenting the block to use current dist folder */

  stage ('build') {
    sh '$(npm bin)/ng build --prod'
  }

  stage ('build image') {
    sh '''
      mkdir dist/nginx-cfg
      cp nginx/status.conf dist/nginx-cfg
      
      oc start-build refarch-uiux-angular-rhel --from-dir=dist --follow
    '''
  }
}
